#! /usr/bin/env python
#
# Convert bib file to HTML
#
# TODO
#  take out tex fragments, backslash, braces etc
#  convert tex accents to HTML accents
#  do string substitution using templates
#  better handling of different reference types
#  probably needs more rigour in the HTML code
#  use CSS

import Bibliography
import BibEntry
import BibTeX
import string
import sys
import time
import optparse


str = ""

def append(s):
	global str

	str += s

def append_nl(s):
	global str

	str += s + '\n'

class HBibEntry(BibEntry.BibEntry):

	def __init__(self, be):
		self.fieldDict = be.fieldDict

	def display(self):
		append( "<p>" )
		# put title
		if self.getURL():
			append( '<a href="%s"><i>"%s"</i></a>, ' % (self.getURL(), self.getTitle()) )
		else:
			append( '<i>"%s"</i>, ' % self.getTitle() )

		# put authors
		append( self.getAuthors() + '.  ' )
		month = self.getMonthName()
		year = self.getYear()

		# put more fields
		for k in ['Journal', 'Volume', 'Number', 'Booktitle',
			'Address', 'Institution']:

			if k in self.fieldDict:
				append( self.fieldDict[k].strip('"') + ', ' )
		eds = self.getEditorsNames()
		if eds:
			append("eds. " + eds + ', ')
		if month:
			append( month )
			if year > 0:
				append( " " + `year` )
		else:
			if year > 0:
				append( ", " + `year` )
		append( " (%s)" % be.getKey() )
		append_nl( "</p>" )



## parse switches
p = optparse.OptionParser()
p.add_option('--highlight', dest='highlight', action='store', type='str',
             help='highlight the specified word in the output')
#p.add_option('--resolve', dest='resolve', action='store_true',
#             help='resolve cross reference entries')
p.set_defaults(highlight=None)
(opts, args) = p.parse_args()
globals().update(opts.__dict__)

if len(args) == 0 and sys.stdin.isatty():
	p.print_help()
	sys.exit(0)

## read the input files
bib = BibTeX.BibTeX()
if args:
	for f in args:
		bib.parseFile(f)
else:
	bib.parseFile()

bib.resolveAbbrev()

## generate HTML
append_nl( "<html>" )
append_nl( "<head>" )
append_nl( "  <title>Bibliography %s</title>" % ( args[0] if args else '(stdin)',) )
append_nl( """  <meta http-equiv="Content-Type" content="text/html charset=iso-8859-1">""" )
append_nl( "</head>" )
append_nl( "<body>" )

for be in bib:
	hb = HBibEntry(be)
	hb.display()

if highlight:
	str = string.replace(str, highlight, """<font color="ff0000">%s</font>""" % highlight)

append_nl( "<hr>" )
append_nl( "<p>Generated by bib2html at %s.  bib2html by Peter Corke</p>" % time.asctime() )
append_nl( "</body>" )
append_nl( "</html>" )

print str
